update workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,17 +2,14 @@ name: Deploy to S3
 
 on:
   push:
-    # Trigger this workflow only on commits with "[build]" in the commit message
     branches:
       - main
-    # Filter commit messages to only run on "[build]" commit
-    # You can modify the regular expression as needed
     paths:
       - "**/*"
-    if: contains(github.event.head_commit.message, '[build]')
 
 jobs:
   build_and_deploy:
+    if: contains(github.event.head_commit.message, '[build]')
     runs-on: ubuntu-latest
 
     steps:
@@ -21,8 +18,6 @@ jobs:
 
     - name: Set up Node.js
       uses: actions/setup-node@v3
-      with:
-        node-version: '16'
 
     - name: Install dependencies
       run: |
@@ -32,11 +27,24 @@ jobs:
       run: |
         npm run build
 
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v2
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ secrets.AWS_REGION }}
+
+    - name: Validate AWS credentials
+      run: |
+        if aws sts get-caller-identity > /dev/null 2>&1; then
+          echo "AWS credentials are valid."
+        else
+          echo "Error: AWS credentials are invalid or not configured."
+          exit 1
+        fi
+
     - name: Deploy to S3
       env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: ${{ secrets.AWS_REGION }}
         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
       run: |
-        aws s3 sync ./build/ s3://$S3_BUCKET_NAME/ --delete --exclude "*.git/*"
+        aws s3 sync ./build/ s3://$S3_BUCKET_NAME/ --delete --exclude ".git/*"
